#
# Custom action that use a dockerfile
# GitHub action will build the image from the dockerfile
#
# See: https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-docker-container-action
#
name: 'Hello Rocky'
description: 'Using rocky linux.'

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

outputs:
  time: # id of output
    description: 'The time we greeted you'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
  env:
    MY_ENV_1: "Value1"
    MY_ENV_2: "Value2"
