name: Caller
run-name: "[Caller] ${{ github.ref }}"

on:
  workflow_dispatch:

jobs:
  job_1:
    name: Ubuntu gcc-12
    uses: ./.github/workflows/CallMe.yml
    with:
      cc: "gcc-12"
      cxx: "g++-12"

  job_2:
    name: Ubuntu gcc-13
    uses: ./.github/workflows/CallMe.yml
    with:
        cc: "gcc-13"
        cxx: "g++-13"

  job_3:
    name: Ubuntu gcc-14
    uses: ./.github/workflows/CallMe.yml
    with:
        cc: "gcc-14"
        cxx: "g++-14"

  job_4:
    name: Ubuntu clang-14
    uses: ./.github/workflows/CallMe.yml
    with:
      cc:  "clang-18"
      cxx: "clang++-18"
