# Clear the GitHub action cache
# from https://stackoverflow.com/questions/63521430/clear-cache-in-github-actions
# https://github.com/roboflow/supervision/blob/develop/.github/workflows/clear-cache.yml
#
# FIXME: Look like it can only delete 30 cache per run ....
#
name: Clear cache
run-name: "[Clear cache] ${{ github.ref }}"

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        uses: actions/github-script@v7
        with:
          script: |
            console.log(`Starting cleanup cache for branch ${context.ref}`)
            let deletedCount = 0
            let hasNextPage = true

            do {
              // Get of array of cache object
              // The API return maximum 100 elements
              const caches = await github.rest.actions.getActionsCacheList({
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100,
                ref: context.ref
              })

              hasNextPage = caches.length > 100;

              for (const cache of caches.data.actions_caches) {
                console.log(`Deleting cache: ${cache.key} for ${cache.ref} (${cache.size_in_bytes} bytes)`)

                try {
                  await github.rest.actions.deleteActionsCacheById({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    cache_id: cache.id,
                  })
                  deletedCount++
                } catch (error) {
                  console.error(`Failed to delete cache ${cache.key}: ${error.message}`)
                }
              }
            } while(hasNextPage)

            console.log(`Cache cleanup completed. Deleted ${deletedCount} caches.`)
