################################################################################
# Clear the GitHub action cache for a specific PR branche
################################################################################
name: PR Clear cache
run-name: "[PR Clear cache] refs/pull/${{ github.event.pull_request.number }}/merge"

on:
  pull_request:
    types:
      - closed

permissions:
  actions: write

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      # Clone the repo (Required to use custom action in this repo)
      - name: Cloning git repo
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0

      - uses: ./.github/workflows/actions/clear-cache
        with:
          branch: refs/pull/${{ github.event.pull_request.number }}/merge
          github-token: ${{ github.token }}
