name: PR-Test
on: pull_request

jobs:
  example_matrix:
    name: PRBuild
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    steps:
      - run: echo "Hello !"
