name: PR-Test
on: pull_request

jobs:
  example_matrix:
    name: PRBuild
    strategy:
      matrix:
        os: [ubuntu-2022.04, ubuntu-2024.04]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "Hello !"
