###############################################################
# Workflow to test annotation (notice, warning, error)
#
# https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions
#
###############################################################
name: Test-Annotation
on: workflow_dispatch

jobs:
  GenerateAnnotation:
    name: GenerateAnnotation
    runs-on: ubuntu-24.04
    steps:
        - name: Generate Warning
          run: |
            echo "::warning::This is a custom warning."
            echo "::warning title=Hey::This is a custom warning with title."

        - name: Generate Error
          run: |
            echo "::error::This is a custom error."
            echo "::error title=Hey::This is a custom error with title."

        - name: Generate Notices
          run: |
            echo "::notice::This is a custom notice."
            echo "::notice title=Hey::This is a custom notice with title."
