# Workflow example that use a custom "docker" action.
name: UseDocker

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # Clone the repo
      # This is required to use the custom action in this repo.
      - name: Cloning git repo
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      # Use a custom action based on a dockerfile (alpine)
      - name: Hello world action step
        id: alpineDocker
        uses: ./.github/workflows/actions/alpine-docker
        with:
          who-to-greet: 'Mona the Octocat'

      # Use a custom action based on a docker image (rocky)
      - name: Hello world action step
        id: rockerDocker
        uses: ./.github/workflows/actions/rocky-docker
        with:
          who-to-greet: 'YoYo'

        # Use the output from the 'alpineDocker' and  'rockerDocker' step
      - name: Get the output time
        run: |
          echo "The time was ${{ steps.alpineDocker.outputs.time }} from alpine."
          echo "The time was ${{ steps.rockerDocker.outputs.time }} from rocky."
